<br>
<form action="" method="post">
    <h3>Введите значения</h3>
    <input type="text" name="arg1" size="5" value="<?= $arg1 ?>">
    <input type="text" name="arg2" size="5" value="<?= $arg2 ?>">
    =
    <input type="text" readonly size="5" value="<?= $result ?>">
    <br>
    <h3>Выберите действие</h3>
    <input type="submit" name="operation" value="+">
    <input type="submit" name="operation" value="-">
    <input type="submit" name="operation" value="*">
    <input type="submit" name="operation" value="/">
</form>